disableSerialization;
private["_arrayNeeded","_user","_arrayCount","_myInjuries","_item"];
_arrayNeeded = _this select 0;
_user = _arrayNeeded select 0;
_myInjuries = _arrayNeeded select 1;
_arrayCount = _arrayNeeded select 2;
_item = _arrayNeeded select 3;
player removeMagazine _item;
5 cutText ["","PLAIN"];
_myInjuries set [_arrayCount, 0];
_user setVariable ["medical_playerInjuries",_myInjuries,true];
medical_imHealing = false;
[_user] spawn ClientModules_medical_fnc_medicUpdater;
